Enabled schema registry and ksql server.
distributed-technologies/services-kafka pull request #11
Opened 2021-09-15 10:43 UTC by jacobcrawford

2021-09-20 13:12 UTC, klausenbusk commented on .github/workflows/test_create.yaml
> +
Let's remove these two blank lines.

2021-09-20 13:12 UTC, klausenbusk commented on chart/scripts/python_ksql.py
> +from ksql import KSQLAPI
```suggestion
from ksql import KSQLAPI
```

2021-09-20 13:12 UTC, klausenbusk commented on docs/ksql-examples.md
> +```
```suggestion
# Create stream from a kafka topic
```sql
```
Add sql here and for the other examples for syntax highlighting.

Ex:
```sql
CREATE STREAM test_stream_1 (number INT) 
    WITH (KAFKA_TOPIC='topic-test-1', VALUE_FORMAT='JSON'); 
```

2021-09-20 15:03 UTC, skovbakke reviewed
Just a few comments for now

2021-09-21 11:43 UTC, jacobcrawford commented on chart/templates/tests/test-kafka-ksql-pod.yaml
> +{{ if eq .Values.env "test" }}
I guess you are right :)

2021-09-22 08:04 UTC, klausenbusk requested changes
Minor comment, but LGTM 🎉

2021-09-22 12:43 UTC, klausenbusk approved these changes
LGTM 🎉

2021-09-22 12:44 UTC, merged